### ISSUE TITLE
MageTestStand Setup in Travis Build is Fragile

### ISSUE THREAD

**Issue by tkn98** [firegento/firegento-pdf#283]
The command to setup the [MageTestStand](https://github.com/AOEpeople/MageTestStand) fails occasionally in build:

    The command "curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash" exited with 255.
    
Ref: https://travis-ci.org/firegento/firegento-pdf/jobs/88771518
    
Sometimes it's green:

	The command "curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash" exited with 0.

Ref: https://travis-ci.org/firegento/firegento-pdf/jobs/88771512

**Comment by tkn98** [comment]
@sprankhub I created the issue here now, have you reported this upstream, too? I can imagine that multiple users of MageTestStand have / had the same problem.

One fix that could be done is to call the command with [`travis_retry`](http://docs.travis-ci.com/user/build-timeouts/).

**Comment by sprankhub** [comment]
Thanks @tkn98! We already had some people (Fabrizio, Bastian, Vinai) who had a look at it. We discussed it on twitter: https://twitter.com/SimonSprankel/status/605264253696778240. Unfortunately, nobody could solve it. Would you be able and willing to remove the usage of MageTestStand and implement the tests in another manner?

**Comment by tkn98** [comment]
This just quickly to check with `travis_retry`. We might have a different problem as of today because of https://github.com/netz98/n98-magerun/issues/722

**Comment by sprankhub** [comment]
Thanks! But the problem persists: https://travis-ci.org/firegento/firegento-pdf/builds/89210734

**Comment by tkn98** [comment]
So this is making progress, the remaining problem is now that magerun which operates below mage test stand has to switch to mirrors. I think we should fix that problem first, you can keep track of that here: https://github.com/netz98/n98-magerun/issues/722

**Comment by sprankhub** [comment]
The MageTestStand setup should work stable now. Travis still fails though. I created a new issue for the failing Travis CI tests: https://github.com/firegento/firegento-pdf/issues/293
